export function getFlagCode(countryName: string): string {
  const codes: Record<string, string> = {
    'Mexico': 'mx',
    'South Africa': 'za',
    'Korea Republic': 'kr',
    'South Korea': 'kr',
    'Czechia': 'cz',
    'Canada': 'ca',
    'Bosnia and Herzegovina': 'ba',
    'Bosnia & Herzegovina': 'ba',
    'Qatar': 'qa',
    'Switzerland': 'ch',
    'Brazil': 'br',
    'Morocco': 'ma',
    'Scotland': 'gb-sct',
    'Haiti': 'ht',
    'United States': 'us',
    'USA': 'us',
    'Australia': 'au',
    'Paraguay': 'py',
    'Türkiye': 'tr',
    'Germany': 'de',
    'Ecuador': 'ec',
    'Côte d\'Ivoire': 'ci',
    'Ivory Coast': 'ci',
    'Curaçao': 'cw',
    'Netherlands': 'nl',
    'Japan': 'jp',
    'Tunisia': 'tn',
    'Sweden': 'se',
    'Belgium': 'be',
    'Iran': 'ir',
    'Egypt': 'eg',
    'New Zealand': 'nz',
    'Spain': 'es',
    'Uruguay': 'uy',
    'Saudi Arabia': 'sa',
    'Cape Verde': 'cv',
    'France': 'fr',
    'Norway': 'no',
    'Senegal': 'sn',
    'Iraq': 'iq',
    'Argentina': 'ar',
    'Austria': 'at',
    'Algeria': 'dz',
    'Jordan': 'jo',
    'Portugal': 'pt',
    'Colombia': 'co',
    'Uzbekistan': 'uz',
    'DR Congo': 'cd',
    'England': 'gb-eng',
    'Croatia': 'hr',
    'Ghana': 'gh',
    'Panama': 'pa',
  }
  return codes[countryName] ?? 'un'
}
