export function getFlagEmoji(countryName: string): string {
  const flags: Record<string, string> = {
    'Mexico': '🇲🇽',
    'South Africa': '🇿🇦',
    'Korea Republic': '🇰🇷',
    'Czechia': '🇨🇿',
    'Canada': '🇨🇦',
    'Bosnia and Herzegovina': '🇧🇦',
    'Qatar': '🇶🇦',
    'Switzerland': '🇨🇭',
    'Brazil': '🇧🇷',
    'Morocco': '🇲🇦',
    'Scotland': '🏴',
    'Haiti': '🇭🇹',
    'United States': '🇺🇸',
    'Australia': '🇦🇺',
    'Paraguay': '🇵🇾',
    'Türkiye': '🇹🇷',
    'Germany': '🇩🇪',
    'Ecuador': '🇪🇨',
    'Côte d\'Ivoire': '🇨🇮',
    'Curaçao': '🇨🇼',
    'Netherlands': '🇳🇱',
    'Japan': '🇯🇵',
    'Tunisia': '🇹🇳',
    'Sweden': '🇸🇪',
    'Belgium': '🇧🇪',
    'Iran': '🇮🇷',
    'Egypt': '🇪🇬',
    'New Zealand': '🇳🇿',
    'Spain': '🇪🇸',
    'Uruguay': '🇺🇾',
    'Saudi Arabia': '🇸🇦',
    'Cape Verde': '🇨🇻',
    'France': '🇫🇷',
    'Norway': '🇳🇴',
    'Senegal': '🇸🇳',
    'Iraq': '🇮🇶',
    'Argentina': '🇦🇷',
    'Austria': '🇦🇹',
    'Algeria': '🇩🇿',
    'Jordan': '🇯🇴',
    'Portugal': '🇵🇹',
    'Colombia': '🇨🇴',
    'Uzbekistan': '🇺🇿',
    'DR Congo': '🇨🇩',
    'England': '🏴',
    'Croatia': '🇭🇷',
    'Ghana': '🇬🇭',
    'Panama': '🇵🇦',
  }
  return flags[countryName] ?? '🏳️'
}
